#!/usr/bin/env python

import io
import socket
import sys
import wx

BUFFER_SIZE = 100000
PORT = 12001
DEBUG = False
POS = (0, 0)
SIZE = (590, 590)

class ImageFrame(wx.Frame):
    def __init__(self, pos, size):
        wx.Frame.__init__(self, None, pos=wx.Point(*pos), size=wx.Size(*size), style=wx.STAY_ON_TOP)
        self.bitmap = None
        self.maxlen = 0
        self.server = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.server.bind(("", PORT))
        self.Show()
        self.Bind(wx.EVT_PAINT, self.onPaint)

    def onPaint(self, event):
        wx.CallAfter(self.readUDP)

        if self.bitmap == None:
            return
        dc = wx.PaintDC(self)
        dc.DrawBitmap(self.bitmap, 0, 0)

    def readUDP(self):
        data = self.server.recv(BUFFER_SIZE)
        datalen = len(data)
        if datalen > self.maxlen:
            if DEBUG:
                print("Max image size: {}".format(datalen))
            self.maxlen = datalen
        image = wx.ImageFromStream(io.BytesIO(data), wx.BITMAP_TYPE_JPEG)
        self.bitmap = image.ConvertToBitmap()
        self.Refresh()

app = wx.App(DEBUG)
frame = ImageFrame(POS, SIZE)
app.MainLoop()
